// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/reading-quest/Grownups.tsx": () => import("../components/mockups/reading-quest/Grownups.tsx"),
  "./components/mockups/reading-quest/Home.tsx": () => import("../components/mockups/reading-quest/Home.tsx"),
  "./components/mockups/reading-quest/Session.tsx": () => import("../components/mockups/reading-quest/Session.tsx"),
  "./components/mockups/reading-quest/SessionWordHelp.tsx": () => import("../components/mockups/reading-quest/SessionWordHelp.tsx")
};
